### ISSUE TITLE
Use github-action-psscriptanalyzer to analyze github-action-psscriptanalyzer 

### ISSUE THREAD

**Issue by TylerLeonhardt** [devblackops/github-action-psscriptanalyzer#1]
Since github-action-psscriptanalyzer is a repo with a few PowerShell scripts, I think you have an opportunity to give a real example by running github-action-psscriptanalyzer on the github-action-psscriptanalyzer codebase.

**Comment by devblackops** [comment]
Well if that’s not a “yo dawg...” 😀

I’ll try it out.

**Comment by devblackops** [comment]
Implemented in c807200d2ea3a669c37349ee98aba5343b755bb5 and 860785510c5bd281ae64003a222b3ebab796e56e

**Comment by TylerLeonhardt** [comment]
How about a badge 😊

![Actions Status](https://wdp9fww0r9.execute-api.us-west-2.amazonaws.com/production/badge/devblackops/github-action-psscriptanalyzer)

```
![Actions Status](https://wdp9fww0r9.execute-api.us-west-2.amazonaws.com/production/badge/devblackops/github-action-psscriptanalyzer)
```

From  https://github.com/CultureHQ/github-actions-badge

**Comment by devblackops** [comment]
Nice! Looks like there is already an issue for this on shields. https://github.com/badges/shields/issues/2574

**Comment by TylerLeonhardt** [comment]
Yeah that'd be ideal. Big fan of shields.io 👍

**Comment by alagoutte** [comment]
Update for use yml file ?
