### ISSUE TITLE
No comment push on PR from fork

### ISSUE THREAD

**Issue by alagoutte** [devblackops/github-action-psscriptanalyzer#2]
When use this PSSA Github Actions, there is no comment push on PR
and on github action log, i get : 

```powershell
Invoke-RestMethod : {"message":"Resource not accessible by integration","documentation_url":"https://developer.github.com/v3/issues/comments/#create-a-comment"}
At /entrypoint.ps1:61 char:5
+     Invoke-RestMethod @params > $null
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: POST, Reque\u2026application/json
}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
##[error]Docker run failed with exit code 1
```

You can look https://github.com/PowerAruba/PowerArubaCP/pull/23 and https://github.com/PowerAruba/PowerArubaCP/pull/23/checks

**Comment by devblackops** [comment]
Hi @alagoutte. This errors looks to be some type of permissions issue. Have you setup a custom secret that the action is using? If so, try removing that. `GITHUB_TOKEN` is a built into Actions. There should be no need to create a secret.

**Comment by alagoutte** [comment]
Hi,

There is no secret configured (and it is possible to set a secret start by GITHUB_...)

**Comment by JM2K69** [comment]
Hi I have the same issue with @alagoutte  in my project FreeNas powershell module i try with the line secret and without same issue ? do you have an idea ?

**Comment by alagoutte** [comment]
Hi @devblackops any news about this issue ?

**Comment by alagoutte** [comment]
After some tests, it is coming from GitHub Action limitation on fork repo
You don't have GITHUB_TOKEN on PR from a fork (it is a limited to read...)
